language: node_js
node_js:
  - 12.17.0
before_install: npm install -g grunt-cli
script:
  - npm run test
  - npm run test:coverage
notifications:
  email: false
  slack:
    secure: UNWilS66pVbi5wOmiUypOyS6RNs/KdQ+jj0jpDtA3BdVHP8pkSzdvJA7WE3Azvd5VxSeWRJRVT9VK8gFhfek9+u/uPFZp/B4XF00ELLspvS/yZu4L/T+9XDgsenN01iRVmC8cfxX90LEzCohDJF2tX0CQuk6eDhFsby8CiNpnFr3MRed31+/xqwvRbI78b1XrKg62ojK4KpzvpqlANnbZEW67MZ6KI/9rm5ZsXrzDyzrfCmYnkq2/XOdVgMTFVteK6wAuAizVVwh2azh7UrkltgL4SwV/eIuBdheM+TgmSQyWi3ejLzZFPQC1ukS4ghfFdRPIWm3FrXgaOWyCxGHCD9ROBW/17T5Acs3SPnyICmcBAwmnCJqvUU9kFabWakl8g43TNwWx/i0QIKAJJL8f6sCIWhw7vCOpiY4Eau887RU2VDx840iVh1XysWSBVCKG+o5j/f6oBjmjAFwlNYppbcE6oDm506/f0tallEIjpUZQq9LmPDhHcunfq7WaGE7pIb6VV+BCMMxCS6j8YFiQOfCm2CMYiWOwcAGEFwzTKfQ6lDEfHQruPLWJoCQ44s1dT3Q3U3k+1jmGiuWuhyKLDIeWSZGA/cZ6knefL1aFsz5418R9LXGNqgtplbeM9szYulTi5vOVoo8q6okKXC3r7t8dCBq6B8qz9oZVwj21SA=
